# Generated by Django 3.2.8 on 2022-01-09 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import routes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(validators=[routes.models.CustomValidator.validate_route_url], verbose_name='Adres url trasy:')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa trasy:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis trasy:')),
                ('is_published', models.BooleanField(default=False, verbose_name='Opublikować?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Usunąć?')),
                ('date_published', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data publikacji:')),
                ('date_created', models.DateTimeField(editable=False, verbose_name='Data utworzenia:')),
                ('last_modyfied', models.DateTimeField(blank=True, null=True, verbose_name='Data modyfikacji:')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik:')),
            ],
            options={
                'verbose_name': 'Trasa',
                'verbose_name_plural': 'Trasy',
                'get_latest_by': '-date_created',
                'unique_together': {('created_by', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść komentarza:')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Usunąć?')),
                ('date_created', models.DateTimeField(editable=False, verbose_name='Data utworzenia:')),
                ('last_modyfied', models.DateTimeField(blank=True, null=True, verbose_name='Data modyfikacji:')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik:')),
                ('referenced_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route', verbose_name='Trasa:')),
            ],
            options={
                'verbose_name': 'Komentarz',
                'verbose_name_plural': 'Komentarze',
                'get_latest_by': '-date_created',
            },
        ),
        migrations.CreateModel(
            name='RouteRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Ocena:')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Usunąć?')),
                ('date_created', models.DateTimeField(editable=False, verbose_name='Data utworzenia:')),
                ('last_modyfied', models.DateTimeField(blank=True, null=True, verbose_name='Data modyfikacji:')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik:')),
                ('referenced_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route', verbose_name='Trasa:')),
            ],
            options={
                'verbose_name': 'Ocena trasy',
                'verbose_name_plural': 'Oceny tras',
                'get_latest_by': '-date_created',
                'unique_together': {('created_by', 'referenced_route')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Usunąć?')),
                ('date_created', models.DateTimeField(editable=False, verbose_name='Data utworzenia:')),
                ('last_modyfied', models.DateTimeField(blank=True, null=True, verbose_name='Data modyfikacji:')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik:')),
                ('referenced_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route', verbose_name='Trasa:')),
            ],
            options={
                'verbose_name': 'Ulubiona trasa',
                'verbose_name_plural': 'Ulubione trasy',
                'get_latest_by': '-date_created',
                'unique_together': {('created_by', 'referenced_route')},
            },
        ),
        migrations.CreateModel(
            name='CommentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(-1, '-1'), (1, '1')], default=1, verbose_name='Ocena:')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Usunąć?')),
                ('date_created', models.DateTimeField(editable=False, verbose_name='Data utworzenia:')),
                ('last_modyfied', models.DateTimeField(blank=True, null=True, verbose_name='Data modyfikacji:')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik:')),
                ('referenced_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.comment', verbose_name='Komentarz:')),
            ],
            options={
                'verbose_name': 'Ocena komentarza',
                'verbose_name_plural': 'Oceny komentarzy',
                'get_latest_by': '-date_created',
                'unique_together': {('created_by', 'referenced_comment')},
            },
        ),
    ]
